/**
 * Playwright reftest runner — replaces the Karma + Mocha testrunner.
 *
 * For every reftest HTML page (tests/reftests/**, minus ignore.txt entries):
 *   1. Load the page in an 800×600 viewport with `?selenium&run=false&reftest`
 *      query (test.js exposes `html2canvas` on HTMLElement and disables
 *      autorun).
 *   2. Render the page via the library exactly like the old in-browser mocha
 *      suite: `contentWindow.html2canvas(documentElement, {...})`.
 *   3. Assert the canvas is untainted (getImageData succeeds).
 *   4. POST the PNG to the screenshot server (tests/server.ts), which writes
 *      tmp/reftests/<test>.png — the same artifact the CI upload and the
 *      reftest-diff harness consume.
 *
 * Screenshot metadata keeps the `platform.name`/`platform.version` shape of
 * the Karma uploads so downstream consumers (metadata folder, result list)
 * need no changes.
 *
 * Usage: pnpm reftests [-- --browser=chrome]  (default: chromium; also
 * firefox, webkit — mirroring the old TARGET_BROWSER matrix).
 */

import { chromium, firefox, webkit } from 'playwright';
import { createDefaultValidator } from '../src/index';
import { mkdir } from 'fs/promises';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '../');

interface ReftestList {
    testList: string[];
    ignoredTests: { [key: string]: string[] };
}

// The reftest pages proxy cross-origin images through localhost:8081; the
// default Validator rejects localhost proxies, so relax it like the Karma
// runner did (tests/testrunner.ts).
const reftestValidator = createDefaultValidator({ allowLocalhostProxy: true });

const loadTestList = async (): Promise<ReftestList> => {
    // build/reftests.js is generated by `pnpm build:create-reftest-list` as
    // plain ESM exports.
    const modulePath = resolve(root, 'build/reftests.js');
    const raw = (await import(`${modulePath}?${Date.now()}`)) as unknown as ReftestList;
    return { testList: raw.testList, ignoredTests: raw.ignoredTests };
};

interface BrowserSelection {
    engine: typeof chromium | typeof firefox | typeof webkit;
    platformName: string;
}

const selectBrowser = (requested: string): BrowserSelection => {
    switch (requested.toLowerCase()) {
        case 'chrome':
        case 'chromium':
            return { engine: chromium, platformName: 'Chrome' };
        case 'firefox':
            return { engine: firefox, platformName: 'Firefox' };
        case 'safari':
        case 'webkit':
            return { engine: webkit, platformName: 'Safari' };
        default:
            throw new Error(`Unknown browser "${requested}". Supported: chromium, firefox, webkit (default: chromium)`);
    }
};

const isIgnored = (ignoredTests: ReftestList['ignoredTests'], url: string, platformName: string): boolean => {
    const entry = ignoredTests[url];
    if (!Array.isArray(entry)) {
        return false;
    }
    return entry.indexOf(platformName) !== -1;
};

const main = async (): Promise<void> => {
    const args = process.argv.slice(2);
    const browserArg = args.find((arg) => arg.startsWith('--browser='))?.split('=')[1] ?? 'chrome';
    const { engine, platformName } = selectBrowser(browserArg);

    const { testList, ignoredTests } = await loadTestList();
    const tests = testList.filter((url) => !isIgnored(ignoredTests, url, platformName));
    if (tests.length === 0) {
        throw new Error('No reftests found — run "pnpm build" first (generates build/reftests.js)');
    }

    await mkdir(resolve(root, 'tmp/reftests'), { recursive: true });
    await mkdir(resolve(root, 'tmp/reftests/metadata'), { recursive: true });

    // Static reftest pages come from a dedicated static app (port 8080); the
    // screenshot app (8000) only receives uploads; the CORS app (8081) backs
    // the image proxy — the same service split as the Karma-era runner.
    //
    // The static app deliberately does NOT mount /redirect-image: under Karma
    // that route never resolved either, and the page renders it as a broken
    // image (which the captures rely on — a live redirect would taint the
    // canvas with the cross-origin target).
    const express = (await import('express')).default;
    const path = await import('path');
    const serveIndex = (await import('serve-index')).default;
    const staticApp = express();
    staticApp.use('/', serveIndex(resolve(root, 'tests/reftests'), { icons: true }));
    staticApp.use('/', express.static(resolve(root)));
    staticApp.use('/assets', express.static(resolve(root, 'tests/assets')));
    const staticServer = staticApp.listen(8080);
    const { screenshotApp, corsApp } = await import('./server');
    const screenshotServer = screenshotApp.listen(8000);
    const corsServer = corsApp.listen(8081);
    await new Promise<void>((onListening) => staticServer.once('listening', onListening));

    let browser: Awaited<ReturnType<typeof engine.launch>>;
    try {
        browser = await engine.launch({ headless: true });
    } catch (error) {
        // Distinguish "browser binary missing" from a real launch failure —
        // CI and local runs both hit this when `playwright install` was not
        // run for the requested engine after a Playwright upgrade.
        if (error instanceof Error && /Executable doesn't exist/.test(error.message)) {
            throw new Error(
                `Playwright browser for "${browserArg}" is not installed. Run: pnpm exec playwright install ${browserArg}`,
                { cause: error }
            );
        }
        throw error;
    }
    const context = await browser.newContext({ viewport: { width: 800, height: 600 } });
    const originUrl = 'http://localhost:8080';
    const runnerUrl = 'http://localhost:8000';

    let failures = 0;
    const failed: string[] = [];

    try {
        for (const url of tests) {
            const page = await context.newPage();
            const pageErrors: string[] = [];
            page.on('pageerror', (error) => pageErrors.push(error.message));

            try {
                // A same-origin document is required for the iframe injection;
                // about:blank would leave the iframe on a null origin where
                // the relative test.js script src fails.
                await page.goto(`${originUrl}/tests/rangetest.html?runner`, { waitUntil: 'load' });
                const result = await page.evaluateHandle(
                    /* browser-side render + upload, mirrors tests/testrunner.ts */
                    async ({ url, runnerUrl }: { url: string; runnerUrl: string }) => {
                        const iframe = document.createElement('iframe');
                        iframe.width = '800';
                        iframe.height = '600';
                        iframe.style.visibility = 'hidden';
                        iframe.style.position = 'fixed';
                        iframe.style.left = '10000px';
                        iframe.src = `${url}?selenium&run=false&reftest&${Math.random()}`;

                        const loaded = new Promise<void>((onLoad) => {
                            iframe.onload = () => onLoad();
                        });
                        document.body.appendChild(iframe);
                        await loaded;

                        try {
                            const contentWindow = iframe.contentWindow!;
                            contentWindow.addEventListener('unhandledrejection', (event) => {
                                throw new Error(`unhandledrejection: ${JSON.stringify(event.reason)}`);
                            });
                            const canvas = await (
                                contentWindow as Window & {
                                    html2canvas: (
                                        el: HTMLElement,
                                        opts: Record<string, unknown>
                                    ) => Promise<HTMLCanvasElement>;
                                }
                            ).html2canvas(contentWindow.forceElement || contentWindow.document.documentElement, {
                                removeContainer: true,
                                backgroundColor: '#ffffff',
                                proxy: 'http://localhost:8081/proxy',
                                validator: (
                                    contentWindow as unknown as Window & {
                                        html2canvasExports?: { createDefaultValidator: (config?: object) => unknown };
                                    }
                                ).html2canvasExports?.createDefaultValidator({ allowLocalhostProxy: true }),
                                ...(contentWindow.h2cOptions || {})
                            });

                            // untaint check
                            (canvas.getContext('2d') as CanvasRenderingContext2D).getImageData(
                                0,
                                0,
                                canvas.width,
                                canvas.height
                            );

                            return canvas.toDataURL();
                        } finally {
                            iframe.remove();
                        }
                    },
                    { url, runnerUrl }
                );

                const dataUrl = (await result.jsonValue()) as string;
                if (typeof dataUrl !== 'string' || !dataUrl.startsWith('data:image/png')) {
                    throw new Error(`Unexpected canvas payload for ${url}`);
                }

                const screenshotBody = {
                    screenshot: dataUrl,
                    test: url,
                    platform: { name: platformName, version: browser.version() },
                    devicePixelRatio: 1,
                    windowWidth: 800,
                    windowHeight: 600
                };
                const response = await page.request.post(`${runnerUrl}/screenshot`, {
                    data: screenshotBody,
                    headers: { 'Content-Type': 'application/json' }
                });
                if (response.status() !== 200) {
                    throw new Error(`Screenshot upload failed with status ${response.status()}`);
                }
            } catch (error) {
                failures++;
                failed.push(url);
                const detail = pageErrors.length > 0 ? ` | page errors: ${pageErrors.join('; ')}` : '';
                console.error(`FAIL ${url}: ${error instanceof Error ? error.message : error}${detail}`);
            } finally {
                await page.close();
            }
        }
    } finally {
        await browser.close();
        staticServer.close();
        screenshotServer.close();
        corsServer.close();
    }

    // eslint-disable-next-line no-console -- summary line for CI logs
    console.info(`\n${tests.length - failures}/${tests.length} reftests captured (${platformName})`);
    if (failures > 0) {
        console.error(`Failed tests:\n  ${failed.join('\n  ')}`);
        process.exit(1);
    }
};

main().catch((error) => {
    console.error(error);
    process.exit(1);
});
