import { describe, it, expect } from 'vitest';
import { TokenType } from '../token-types';
import {
    LEFT_PARENTHESIS_TOKEN,
    RIGHT_PARENTHESIS_TOKEN,
    COMMA_TOKEN,
    COLON_TOKEN,
    SEMICOLON_TOKEN,
    LEFT_CURLY_BRACKET_TOKEN,
    RIGHT_CURLY_BRACKET_TOKEN,
    LEFT_SQUARE_BRACKET_TOKEN,
    RIGHT_SQUARE_BRACKET_TOKEN,
    WHITESPACE_TOKEN,
    EOF_TOKEN,
    BAD_URL_TOKEN,
    BAD_STRING_TOKEN,
    CDO_TOKEN,
    CDC_TOKEN,
    SUFFIX_MATCH_TOKEN,
    PREFIX_MATCH_TOKEN,
    COLUMN_TOKEN,
    DASH_MATCH_TOKEN,
    INCLUDE_MATCH_TOKEN,
    SUBSTRING_MATCH_TOKEN
} from '../token-singletons';

describe('token singletons', () => {
    const cases: [string, { type: TokenType }, TokenType][] = [
        ['LEFT_PARENTHESIS_TOKEN', LEFT_PARENTHESIS_TOKEN, TokenType.LEFT_PARENTHESIS_TOKEN],
        ['RIGHT_PARENTHESIS_TOKEN', RIGHT_PARENTHESIS_TOKEN, TokenType.RIGHT_PARENTHESIS_TOKEN],
        ['COMMA_TOKEN', COMMA_TOKEN, TokenType.COMMA_TOKEN],
        ['COLON_TOKEN', COLON_TOKEN, TokenType.COLON_TOKEN],
        ['SEMICOLON_TOKEN', SEMICOLON_TOKEN, TokenType.SEMICOLON_TOKEN],
        ['LEFT_CURLY_BRACKET_TOKEN', LEFT_CURLY_BRACKET_TOKEN, TokenType.LEFT_CURLY_BRACKET_TOKEN],
        ['RIGHT_CURLY_BRACKET_TOKEN', RIGHT_CURLY_BRACKET_TOKEN, TokenType.RIGHT_CURLY_BRACKET_TOKEN],
        ['LEFT_SQUARE_BRACKET_TOKEN', LEFT_SQUARE_BRACKET_TOKEN, TokenType.LEFT_SQUARE_BRACKET_TOKEN],
        ['RIGHT_SQUARE_BRACKET_TOKEN', RIGHT_SQUARE_BRACKET_TOKEN, TokenType.RIGHT_SQUARE_BRACKET_TOKEN],
        ['WHITESPACE_TOKEN', WHITESPACE_TOKEN, TokenType.WHITESPACE_TOKEN],
        ['EOF_TOKEN', EOF_TOKEN, TokenType.EOF_TOKEN],
        ['BAD_URL_TOKEN', BAD_URL_TOKEN, TokenType.BAD_URL_TOKEN],
        ['BAD_STRING_TOKEN', BAD_STRING_TOKEN, TokenType.BAD_STRING_TOKEN],
        ['CDO_TOKEN', CDO_TOKEN, TokenType.CDO_TOKEN],
        ['CDC_TOKEN', CDC_TOKEN, TokenType.CDC_TOKEN],
        ['SUFFIX_MATCH_TOKEN', SUFFIX_MATCH_TOKEN, TokenType.SUFFIX_MATCH_TOKEN],
        ['PREFIX_MATCH_TOKEN', PREFIX_MATCH_TOKEN, TokenType.PREFIX_MATCH_TOKEN],
        ['COLUMN_TOKEN', COLUMN_TOKEN, TokenType.COLUMN_TOKEN],
        ['DASH_MATCH_TOKEN', DASH_MATCH_TOKEN, TokenType.DASH_MATCH_TOKEN],
        ['INCLUDE_MATCH_TOKEN', INCLUDE_MATCH_TOKEN, TokenType.INCLUDE_MATCH_TOKEN],
        ['SUBSTRING_MATCH_TOKEN', SUBSTRING_MATCH_TOKEN, TokenType.SUBSTRING_MATCH_TOKEN]
    ];

    cases.forEach(([name, token, expectedType]) => {
        it(`${name} has correct type`, () => {
            expect(token.type).toBe(expectedType);
        });
    });
});
