import { vi } from 'vitest';

export function createMockContext(): CanvasRenderingContext2D {
    return {
        canvas: {} as HTMLCanvasElement,
        save: vi.fn(),
        restore: vi.fn(),
        translate: vi.fn(),
        scale: vi.fn(),
        rotate: vi.fn(),
        transform: vi.fn(),
        setTransform: vi.fn(),
        resetTransform: vi.fn(),
        clip: vi.fn(),
        drawImage: vi.fn(),
        fillText: vi.fn(),
        strokeText: vi.fn(),
        measureText: vi.fn().mockReturnValue({ width: 50 } as TextMetrics),
        fillRect: vi.fn(),
        strokeRect: vi.fn(),
        clearRect: vi.fn(),
        fill: vi.fn(),
        stroke: vi.fn(),
        beginPath: vi.fn(),
        closePath: vi.fn(),
        moveTo: vi.fn(),
        lineTo: vi.fn(),
        arc: vi.fn(),
        arcTo: vi.fn(),
        bezierCurveTo: vi.fn(),
        quadraticCurveTo: vi.fn(),
        ellipse: vi.fn(),
        rect: vi.fn(),
        createLinearGradient: vi.fn().mockReturnValue({ addColorStop: vi.fn() } as unknown as CanvasGradient),
        createRadialGradient: vi.fn().mockReturnValue({ addColorStop: vi.fn() } as unknown as CanvasGradient),
        createPattern: vi.fn().mockReturnValue({} as CanvasPattern),
        createImageData: vi.fn().mockReturnValue({ data: new Uint8ClampedArray(0) } as ImageData),
        getImageData: vi.fn().mockReturnValue({ data: new Uint8ClampedArray(0) } as ImageData),
        putImageData: vi.fn(),
        globalAlpha: 1,
        globalCompositeOperation: 'source-over',
        fillStyle: '',
        strokeStyle: '',
        lineWidth: 1,
        lineCap: 'butt' as CanvasLineCap,
        lineJoin: 'miter' as CanvasLineJoin,
        miterLimit: 10,
        lineDashOffset: 0,
        font: '',
        textAlign: 'start' as CanvasTextAlign,
        textBaseline: 'alphabetic' as CanvasTextBaseline,
        direction: 'inherit' as CanvasDirection,
        imageSmoothingEnabled: true,
        imageSmoothingQuality: 'low' as ImageSmoothingQuality,
        filter: 'none',
        shadowBlur: 0,
        shadowColor: '',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        getTransform: vi.fn().mockReturnValue({ a: 1, b: 0, c: 0, d: 1, e: 0, f: 0 } as DOMMatrix),
        setLineDash: vi.fn(),
        getLineDash: vi.fn().mockReturnValue([]),
        isPointInPath: vi.fn().mockReturnValue(false),
        isPointInStroke: vi.fn().mockReturnValue(false),
        drawFocusIfNeeded: vi.fn(),
        scrollPathIntoView: vi.fn(),
        createConicGradient: vi.fn().mockReturnValue({ addColorStop: vi.fn() } as unknown as CanvasGradient),
        getContextAttributes: vi.fn().mockReturnValue({}),
        roundRect: vi.fn(),
        setAlpha: vi.fn(),
        setCompositeOperation: vi.fn(),
        setFillColor: vi.fn(),
        setStrokeColor: vi.fn(),
        setLineWidth: vi.fn(),
        setLineCap: vi.fn(),
        setLineJoin: vi.fn(),
        setMiterLimit: vi.fn(),
        setShadow: vi.fn(),
        clipPath: undefined,
        createImageBitmap: undefined,
        addHitRegion: vi.fn(),
        removeHitRegion: vi.fn(),
        clearHitRegions: vi.fn(),
    } as unknown as CanvasRenderingContext2D;
}
